version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8081:80"
  frontend:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - '../4-container/frontend/dist:/usr/share/nginx/html'
