version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8081:80"
  frontend:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - '../4-complete/frontend/dist:/usr/share/nginx/html'
      - '../4-complete/frontend/nginx.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - backend
